if __name__ == "__main__":

    import ROOT
    import argparse

    fW=ROOT.TFile("files_nominal/W.root","r")
    fW_jfru=ROOT.TFile("files_nominal/Wunscaled_jfru.root","r")
    fW_jfrd=ROOT.TFile("files_nominal/Wunscaled_jfrd.root","r")
    fout_jfru=ROOT.TFile("files_nominal/W_jfru.root","recreate")

    hW0jet=fW.Get("mt_0jet/W")
    hW0jet_u=fW_jfru.Get("mt_0jet/W_CMS_htt_jetToTauFake_13TeVUp")
    hW0jet_d=fW_jfrd.Get("mt_0jet/W_CMS_htt_jetToTauFake_13TeVDown")
    hW0jet_u.Scale(hW0jet.Integral()/hW0jet_u.Integral())
    hW0jet_d.Scale(hW0jet.Integral()/hW0jet_d.Integral())

    hW1jet=fW.Get("mt_boosted/W")
    hW1jet_u=fW_jfru.Get("mt_boosted/W_CMS_htt_jetToTauFake_13TeVUp")
    hW1jet_d=fW_jfrd.Get("mt_boosted/W_CMS_htt_jetToTauFake_13TeVDown")
    hW1jet_u.Scale(hW1jet.Integral()/hW1jet_u.Integral())
    hW1jet_d.Scale(hW1jet.Integral()/hW1jet_d.Integral())

    hW2jet=fW.Get("mt_vbf/W")
    hW2jet_u=fW_jfru.Get("mt_vbf/W_CMS_htt_jetToTauFake_13TeVUp")
    hW2jet_d=fW_jfrd.Get("mt_vbf/W_CMS_htt_jetToTauFake_13TeVDown")
    hW2jet_u.Scale(hW2jet.Integral()/hW2jet_u.Integral())
    hW2jet_d.Scale(hW2jet.Integral()/hW2jet_d.Integral())

    hW3jet=fW.Get("mt_antiiso_0jet_cr/W")
    hW3jet_u=fW_jfru.Get("mt_antiiso_0jet_cr/W_CMS_htt_jetToTauFake_13TeVUp")
    hW3jet_d=fW_jfrd.Get("mt_antiiso_0jet_cr/W_CMS_htt_jetToTauFake_13TeVDown")
    hW3jet_u.Scale(hW3jet.Integral()/hW3jet_u.Integral())
    hW3jet_d.Scale(hW3jet.Integral()/hW3jet_d.Integral())

    hW4jet=fW.Get("mt_antiiso_boosted_cr/W")
    hW4jet_u=fW_jfru.Get("mt_antiiso_boosted_cr/W_CMS_htt_jetToTauFake_13TeVUp")
    hW4jet_d=fW_jfrd.Get("mt_antiiso_boosted_cr/W_CMS_htt_jetToTauFake_13TeVDown")
    hW4jet_u.Scale(hW4jet.Integral()/hW4jet_u.Integral())
    hW4jet_d.Scale(hW4jet.Integral()/hW4jet_d.Integral())

    hW5jet=fW.Get("mt_antiiso_vbf_cr/W")
    hW5jet_u=fW_jfru.Get("mt_antiiso_vbf_cr/W_CMS_htt_jetToTauFake_13TeVUp")
    hW5jet_d=fW_jfrd.Get("mt_antiiso_vbf_cr/W_CMS_htt_jetToTauFake_13TeVDown")
    hW5jet_u.Scale(hW5jet.Integral()/hW5jet_u.Integral())
    hW5jet_d.Scale(hW5jet.Integral()/hW5jet_d.Integral())

    #hW6jet=fW.Get("mt_wjets_0jet_cr/W")
    #hW6jet_u=fW_jfru.Get("mt_wjets_0jet_cr/W_CMS_htt_jetToTauFake_13TeVUp")
    #hW6jet_d=fW_jfrd.Get("mt_wjets_0jet_cr/W_CMS_htt_jetToTauFake_13TeVDown")
    #hW6jet_u.Scale(hW6jet.Integral()/hW6jet_u.Integral())
    #hW6jet_d.Scale(hW6jet.Integral()/hW6jet_d.Integral())

    #hW7jet=fW.Get("mt_wjets_boosted_cr/W")
    #hW7jet_u=fW_jfru.Get("mt_wjets_boosted_cr/W_CMS_htt_jetToTauFake_13TeVUp")
    #hW7jet_d=fW_jfrd.Get("mt_wjets_booste_cr/W_CMS_htt_jetToTauFake_13TeVDown")
    #hW7jet_u.Scale(hW7jet.Integral()/hW7jet_u.Integral())
    #hW7jet_d.Scale(hW7jet.Integral()/hW7jet_d.Integral())

    #hW8jet=fW.Get("mt_wjets_vbf_cr/W")
    #hW8jet_u=fW_jfru.Get("mt_wjets_vbf_cr/W_CMS_htt_jetToTauFake_13TeVUp")
    #hW8jet_d=fW_jfrd.Get("mt_wjets_vbf_cr/W_CMS_htt_jetToTauFake_13TeVDown")
    #hW8jet_u.Scale(hW8jet.Integral()/hW8jet_u.Integral())
    #hW8jet_d.Scale(hW8jet.Integral()/hW8jet_d.Integral())

    fout_jfru.cd()
    dir0OS=fout_jfru.mkdir("mt_0jet")
    dir0OS.cd()
    hW0jet_u.SetName("W_CMS_htt_jetToTauFake_13TeVUp")
    hW0jet_u.Write()
    hW0jet_d.SetName("W_CMS_htt_jetToTauFake_13TeVDown")
    hW0jet_d.Write()
    dir1OS=fout_jfru.mkdir("mt_boosted")
    dir1OS.cd()
    hW1jet_u.SetName("W_CMS_htt_jetToTauFake_13TeVUp")
    hW1jet_u.Write()
    hW1jet_d.SetName("W_CMS_htt_jetToTauFake_13TeVDown")
    hW1jet_d.Write()
    dir2OS=fout_jfru.mkdir("mt_vbf")
    dir2OS.cd()
    hW2jet_u.SetName("W_CMS_htt_jetToTauFake_13TeVUp")
    hW2jet_u.Write()
    hW2jet_d.SetName("W_CMS_htt_jetToTauFake_13TeVDown")
    hW2jet_d.Write()

    dir3OS=fout_jfru.mkdir("mt_antiiso_0jet_cr")
    dir3OS.cd()
    hW3jet_u.SetName("W_CMS_htt_jetToTauFake_13TeVUp")
    hW3jet_u.Write()
    hW3jet_d.SetName("W_CMS_htt_jetToTauFake_13TeVDown")
    hW3jet_d.Write()
    dir4OS=fout_jfru.mkdir("mt_antiiso_boosted_cr")
    dir4OS.cd()
    hW4jet_u.SetName("W_CMS_htt_jetToTauFake_13TeVUp")
    hW4jet_u.Write()
    hW4jet_d.SetName("W_CMS_htt_jetToTauFake_13TeVDown")
    hW4jet_d.Write()
    dir5OS=fout_jfru.mkdir("mt_antiiso_vbf_cr")
    dir5OS.cd()
    hW5jet_u.SetName("W_CMS_htt_jetToTauFake_13TeVUp")
    hW5jet_u.Write()
    hW5jet_d.SetName("W_CMS_htt_jetToTauFake_13TeVDown")
    hW5jet_d.Write()


