float mjj_JESDown,mjj_JESUp,jdeta_JESDown,jdeta_JESUp,metphi_JESDown,metphi_JESUp,met_JESDown,met_JESUp,metphi_UESDown,metphi_UESUp,met_UESDown,met_UESUp,amcatNLO_weight,genM,genpT,pt_top1,pt_top2,filterIsoMu24,filterIsoTkMu24,numGenJets,filterIsoMu22,filterIsoTkMu22,tZTTGenDR,metcov00,metcov01,metcov11;
float Rivet_stage1_cat_pTjet30GeV,Rivet_stage0_cat, Rivet_higgsPt, Rivet_nJets30;
float m_sv_ClusteredMet_UP, m_sv_ClusteredMet_DOWN, m_sv_UncMet_UP, m_sv_UncMet_DOWN, pt_sv_ClusteredMet_UP, pt_sv_ClusteredMet_DOWN, pt_sv_UncMet_UP, pt_sv_UncMet_DOWN;
float id_m_medium_1, id_m_medium2016_1;
float byVLooseIsolationRerunMVArun2v1DBoldDMwLT_2, byVTightIsolationRerunMVArun2v1DBoldDMwLT_2, byLooseIsolationRerunMVArun2v1DBoldDMwLT_2, byMediumIsolationRerunMVArun2v1DBoldDMwLT_2, byTightIsolationRerunMVArun2v1DBoldDMwLT_2, byVVTightIsolationRerunMVArun2v1DBoldDMwLT_2,byIsolationRerunMVA3oldDMwLTraw_2;
float matchIsoMu22eta2p1_1,matchIsoTkMu22eta2p1_1,matchIsoMu22_1,matchIsoTkMu22_1,matchIsoMu24_1,matchIsoTkMu24_1,matchIsoMu19Tau20_1,matchIsoMu21Tau20_1,filterIsoMu22eta2p1_1,filterIsoTkMu22eta2p1_1,filterIsoMu22_1,filterIsoTkMu22_1,filterIsoMu24_1,filterIsoTkMu24_1,filterIsoMu19Tau20_1,filterIsoMu21Tau20_1,passIsoMu22eta2p1,passIsoTkMu22eta2p1,passIsoMu22,passIsoTkMu22,passIsoMu24,passIsoTkMu24,passIsoMu19Tau20,passIsoMu21Tau20,matchIsoMu19Tau20_2,matchIsoMu21Tau20_2,filterIsoMu19Tau20_2,filterIsoMu21Tau20_2;
int njets_JESDown,njets_JESUp;
float bpt_1, bpt_2, bflavor_1, bflavor_2;
float photonIso_2, puIso_2, chargedIso_2, neutralIso_2,metcor,metcorphi;
float byCombinedIsolationDeltaBetaCorrRaw3Hits_2, byIsolationMVA3oldDMwLTraw_2;
float pt_1,pt_2,px_1,px_2,py_1,py_2,pz_1,pz_2,eta_1,eta_2,phi_1,phi_2,iso_1,e_1,e_2,m_1,m_2,m_sv,m_pfsv,mvamet,mvametphi,m_sv_UP, m_sv_DOWN, m_pfsv_UP, m_pfsv_DOWN, pt_sv, pt_sv_UP, pt_sv_DOWN; 
int gen_match_1, gen_match_2;
//float pu_weight, trg_weight, amcatNLO_weight;
//bool dilepton_veto, extraelec_veto, extramuon_veto;
bool isZmt;
int nbtag;
float genweight;
float gentau_vispt;
int run, lumi, evt;
int nup,njets;
float npv, pt_tt,jpt_1,jdeta,mjj,jpt_2;//mt_2;
float q_1,q_2;
float met, metphi, met_px, met_py;
float tau_HPSisoVTightMVAold, tau_HPSisoLooseMVAold, tau_HPSisoMediumMVAold, tau_HPSisoTightMVAold;
float tau_HPSisoVTightMVAnew, tau_HPSisoLooseMVAnew, tau_HPSisoMediumMVAnew, tau_HPSisoTightMVAnew;
float tau_HPSisoVTightMVAolddR03, tau_HPSisoLooseMVAolddR03, tau_HPSisoMediumMVAolddR03, tau_HPSisoTightMVAolddR03;
float byLooseCombinedIsolationDeltaBetaCorr3Hits_2,byMediumCombinedIsolationDeltaBetaCorr3Hits_2,byTightCombinedIsolationDeltaBetaCorr3Hits_2,byLooseCombinedIsolationDeltaBetaCorr3HitsdR03_2,byMediumCombinedIsolationDeltaBetaCorr3HitsdR03_2,byTightCombinedIsolationDeltaBetaCorr3HitsdR03_2;
float byVLooseIsolationMVArun2v1DBdR03oldDMwLT_2,byVLooseIsolationMVArun2v1DBoldDMwLT_2,byVLooseIsolationMVArun2v1DBnewDMwLT_2;
float byMediumIsolationMVArun2v1DBdR03oldDMwLT_2,byMediumIsolationMVArun2v1DBoldDMwLT_2,byMediumIsolationMVArun2v1DBnewDMwLT_2;
float byLooseIsolationMVArun2v1DBdR03oldDMwLT_2,byLooseIsolationMVArun2v1DBoldDMwLT_2,byLooseIsolationMVArun2v1DBnewDMwLT_2;
float byTightIsolationMVArun2v1DBdR03oldDMwLT_2,byTightIsolationMVArun2v1DBoldDMwLT_2,byTightIsolationMVArun2v1DBnewDMwLT_2;
float byVTightIsolationMVArun2v1DBdR03oldDMwLT_2,byVTightIsolationMVArun2v1DBoldDMwLT_2,byVTightIsolationMVArun2v1DBnewDMwLT_2;
float againstElectronVLooseMVA6_2,againstElectronLooseMVA6_2,againstElectronMediumMVA6_2,againstElectronTightMVA6_2,againstElectronVTightMVA6_2;
float againstMuonLoose3_2,againstMuonTight3_2;
int numChargedIsoCone_2, numChargedSignalCone_2;
float l2_decayMode;
float trackpt_2;//,m_vis;
int tau_id;
float decayModeFindingNewDMs_2,decayModeFinding_2;
float puweight;
float npu;
int NUP;
int njets_JetAbsoluteFlavMapDown,njets_JetAbsoluteMPFBiasDown,njets_JetAbsoluteScaleDown,njets_JetAbsoluteStatDown,njets_JetEnDown,njets_JetFlavorQCDDown,njets_JetFragmentationDown,njets_JetPileUpDataMCDown,njets_JetPileUpPtBBDown,njets_JetPileUpPtEC1Down,njets_JetPileUpPtEC2Down,njets_JetPileUpPtHFDown,njets_JetPileUpPtRefDown,njets_JetRelativeBalDown,njets_JetRelativeFSRDown,njets_JetRelativeJEREC1Down,njets_JetRelativeJEREC2Down,njets_JetRelativeJERHFDown,njets_JetRelativePtBBDown,njets_JetRelativePtEC1Down,njets_JetRelativePtEC2Down,njets_JetRelativePtHFDown,njets_JetRelativeStatECDown,njets_JetRelativeStatFSRDown,njets_JetRelativeStatHFDown,njets_JetSinglePionECALDown,njets_JetSinglePionHCALDown,njets_JetTimePtEtaDown;
int njets_JetAbsoluteFlavMapUp,njets_JetAbsoluteMPFBiasUp,njets_JetAbsoluteScaleUp,njets_JetAbsoluteStatUp,njets_JetEnUp,njets_JetFlavorQCDUp,njets_JetFragmentationUp,njets_JetPileUpDataMCUp,njets_JetPileUpPtBBUp,njets_JetPileUpPtEC1Up,njets_JetPileUpPtEC2Up,njets_JetPileUpPtHFUp,njets_JetPileUpPtRefUp,njets_JetRelativeBalUp,njets_JetRelativeFSRUp,njets_JetRelativeJEREC1Up,njets_JetRelativeJEREC2Up,njets_JetRelativeJERHFUp,njets_JetRelativePtBBUp,njets_JetRelativePtEC1Up,njets_JetRelativePtEC2Up,njets_JetRelativePtHFUp,njets_JetRelativeStatECUp,njets_JetRelativeStatFSRUp,njets_JetRelativeStatHFUp,njets_JetSinglePionECALUp,njets_JetSinglePionHCALUp,njets_JetTimePtEtaUp;
float mjj_JetAbsoluteFlavMapDown,mjj_JetAbsoluteMPFBiasDown,mjj_JetAbsoluteScaleDown,mjj_JetAbsoluteStatDown,mjj_JetEnDown,mjj_JetFlavorQCDDown,mjj_JetFragmentationDown,mjj_JetPileUpDataMCDown,mjj_JetPileUpPtBBDown,mjj_JetPileUpPtEC1Down,mjj_JetPileUpPtEC2Down,mjj_JetPileUpPtHFDown,mjj_JetPileUpPtRefDown,mjj_JetRelativeBalDown,mjj_JetRelativeFSRDown,mjj_JetRelativeJEREC1Down,mjj_JetRelativeJEREC2Down,mjj_JetRelativeJERHFDown,mjj_JetRelativePtBBDown,mjj_JetRelativePtEC1Down,mjj_JetRelativePtEC2Down,mjj_JetRelativePtHFDown,mjj_JetRelativeStatECDown,mjj_JetRelativeStatFSRDown,mjj_JetRelativeStatHFDown,mjj_JetSinglePionECALDown,mjj_JetSinglePionHCALDown,mjj_JetTimePtEtaDown;
float mjj_JetAbsoluteFlavMapUp,mjj_JetAbsoluteMPFBiasUp,mjj_JetAbsoluteScaleUp,mjj_JetAbsoluteStatUp,mjj_JetEnUp,mjj_JetFlavorQCDUp,mjj_JetFragmentationUp,mjj_JetPileUpDataMCUp,mjj_JetPileUpPtBBUp,mjj_JetPileUpPtEC1Up,mjj_JetPileUpPtEC2Up,mjj_JetPileUpPtHFUp,mjj_JetPileUpPtRefUp,mjj_JetRelativeBalUp,mjj_JetRelativeFSRUp,mjj_JetRelativeJEREC1Up,mjj_JetRelativeJEREC2Up,mjj_JetRelativeJERHFUp,mjj_JetRelativePtBBUp,mjj_JetRelativePtEC1Up,mjj_JetRelativePtEC2Up,mjj_JetRelativePtHFUp,mjj_JetRelativeStatECUp,mjj_JetRelativeStatFSRUp,mjj_JetRelativeStatHFUp,mjj_JetSinglePionECALUp,mjj_JetSinglePionHCALUp,mjj_JetTimePtEtaUp;

float pt_1_, pt_2_, eta_1_, eta_2_, phi_1_, phi_2_, m_1_, m_2_, mvis_, metcov00_, metcov01_, metcov11_, weight_, met_, metphi_, fvalue_;
float extraelec_veto, extramuon_veto, dilepton_veto;
float Phi, Phi1, costheta1,costheta2,costhetastar,Q2V1,Q2V2;
float higgs_pT, higgs_m, hjj_pT, hjj_m, dEtajj, dPhijj, cat_0jet, cat_boosted, cat_vbf, cat_inclusive;
float ME_sm_VBF, ME_sm_ggH, ME_bkg, Dbkg_VBF, Dbkg_ggH, NN_disc;


void fillTreeMVA(TTree* BG_Tree, float PT1, float PT2, float ETA1, float ETA2, float PHI1, float PHI2, float M1, float M2, float MET, float METPHI, float METCOV00, float METCOV01, float METCOV11, float MVIS, float TARGET, float WEIGHT) {
   pt_1_=PT1;
   pt_2_=PT2;
   eta_1_=ETA1;
   eta_2_=ETA2;
   pt_1_=PT1;
   pt_2_=PT2;
   phi_1_=PHI1;
   phi_2_=PHI2;
   m_1_=M1;
   m_2_=M2;
   met_=MET;
   metphi_=METPHI;
   mvis_=MVIS;
   metcov00_=METCOV00;
   metcov11_=METCOV11;
   metcov01_=METCOV01;
   weight_=WEIGHT;
   fvalue_=TARGET;
   BG_Tree->Fill();
}



